export const GET_SHOPPING_LIST_START = 'GET_SHOPPING_LIST_START';
export const GET_SHOPPING_LIST_SUCCESS = 'GET_SHOPPING_LIST_SUCCESS';
export const GET_SHOPPING_LIST_FAIL = 'GET_SHOPPING_LIST_FAIL';

export const GET_SHOPPING_ITEM_START = 'GET_SHOPPING_ITEM_START';
export const GET_SHOPPING_ITEM_SUCCESS = 'GET_SHOPPING_ITEM_SUCCESS';
export const GET_SHOPPING_ITEM_FAIL = 'GET_SHOPPING_ITEM_FAIL';

export const ADD_SHOPPING_ITEM_START = 'ADD_SHOPPING_ITEM_START';
export const ADD_SHOPPING_ITEM_SUCCESS = 'ADD_SHOPPING_ITEM_SUCCESS';
export const ADD_SHOPPING_ITEM_FAIL = 'ADD_SHOPPING_ITEM_FAIL';

export const EDIT_SHOPPING_ITEM_START = 'EDIT_SHOPPING_ITEM_START';
export const EDIT_SHOPPING_ITEM_SUCCESS = 'EDIT_SHOPPING_ITEM_SUCCESS';
export const EDIT_SHOPPING_ITEM_FAIL = 'EDIT_SHOPPING_ITEM_FAIL';

export const DELETE_SHOPPING_ITEM_START = 'DELETE_SHOPPING_ITEM_START';
export const DELETE_SHOPPING_ITEM_SUCCESS = 'DELETE_SHOPPING_ITEM_SUCCESS';
export const DELETE_SHOPPING_ITEM_FAIL = 'DELETE_SHOPPING_ITEM_FAIL';
