export const GET_ALL_PARTIES_START = 'GET_ALL_PARTIES_START';
export const GET_ALL_PARTIES_SUCCESS = 'GET_ALL_PARTIES_SUCCESS';
export const GET_ALL_PARTIES_FAIL = 'GET_ALL_PARTIES_FAIL';

export const GET_SINGLE_PARTY_START = 'GET_SINGLE_PARTY_START';
export const GET_SINGLE_PARTY_SUCCESS = 'GET_SINGLE_PARTY_SUCCESS';
export const GET_SINGLE_PARTY_FAIL = 'GET_SINGLE_PARTY_FAIL';

export const ADD_PARTY_START = 'ADD_PARTY_START';
export const ADD_PARTY_SUCCESS = 'ADD_PARTY_SUCCESS';
export const ADD_PARTY_FAIL = 'ADD_PARTY_FAIL';

export const UPDATE_PARTY_START = 'UPDATE_PARTY_START';
export const UPDATE_PARTY_SUCCESS = 'UPDATE_PARTY_SUCCESS';
export const UPDATE_PARTY_FAIL = 'UPDATE_PARTY_FAIL';

export const DELETE_PARTY_START = 'DELETE_PARTY_START';
export const DELETE_PARTY_SUCCESS = 'DELETE_PARTY_SUCCESS';
export const DELETE_PARTY_FAIL = 'DELETE_PARTY_FAIL';
