export const FETCH_MOOD_START = 'FETCH_MOOD_START';
export const FETCH_MOOD_SUCCESS = 'FETCH_MOOD_SUCCESS';
export const FETCH_MOOD_FAIL = 'FETCH_MOOD_FAIL';

export const ADD_MOOD_START = 'ADD_MOOD_START';
export const ADD_MOOD_SUCCESS = 'ADD_MOOD_SUCCESS';
export const ADD_MOOD_FAIL = 'ADD_MOOD_FAIL';

export const EDIT_MOOD_START = 'EDIT_MOOD_START';
export const EDIT_MOOD_SUCCESS = 'EDIT_MOOD_SUCCESS';
export const EDIT_MOOD_FAIL = 'EDIT_MOOD_FAIL';

export const DELETE_MOOD_START = 'DELETE_MOOD_START';
export const DELETE_MOOD_SUCCESS = 'DELETE_MOOD_SUCCESS';
export const DELETE_MOOD_FAIL = 'DELETE_MOOD_FAIL';