export const GET_TODO_LIST_START = 'GET_TODO_LIST_START';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_FAIL = 'GET_TODO_LIST_FAIL';

export const GET_TODO_ITEM_START = 'GET_TODO_ITEM_START';
export const GET_TODO_ITEM_SUCCESS = 'GET_TODO_ITEM_SUCCESS';
export const GET_TODO_ITEM_FAIL = 'GET_TODO_ITEM_FAIL';

export const ADD_TODO_ITEM_START = 'ADD_TODO_ITEM_START';
export const ADD_TODO_ITEM_SUCCESS = 'ADD_TODO_ITEM_SUCCESS';
export const ADD_TODO_ITEM_FAIL = 'ADD_TODO_ITEM_FAIL';

export const EDIT_TODO_ITEM_START = 'EDIT_TODO_ITEM_START';
export const EDIT_TODO_ITEM_SUCCESS = 'EDIT_TODO_ITEM_SUCCESS';
export const EDIT_TODO_ITEM_FAIL = 'EDIT_TODO_ITEM_FAIL';

export const DELETE_TODO_ITEM_START = 'DELETE_TODO_ITEM_START';
export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';
export const DELETE_TODO_ITEM_FAIL = 'DELETE_TODO_ITEM_FAIL';
